---
title: L’instruction 'Throw' ne peut pas omettre l’opérande en dehors d’une instruction 'Catch' ou dans une instruction 'Finally'
ms.date: 07/20/2015
f1_keywords:
- vbc30666
- bc30666
helpviewer_keywords:
- BC30666
ms.assetid: a208a6ea-0e36-4bf1-8984-4de1a0e38a2a
ms.openlocfilehash: 6906cb743e6f36acfbf51a5a38d03bd05fde98e2
ms.sourcegitcommit: 6b308cf6d627d78ee36dbbae8972a310ac7fd6c8
ms.translationtype: MT
ms.contentlocale: fr-FR
ms.lasthandoff: 01/23/2019
ms.locfileid: "54598761"
---
# <a name="throw-statement-cannot-omit-operand-outside-a-catch-statement-or-inside-a-finally-statement"></a>L’instruction 'Throw' ne peut pas omettre l’opérande en dehors d’une instruction 'Catch' ou dans une instruction 'Finally'
Les instructions`Throw` situées en dehors de l’instruction `Catch` doivent fournir le nom d’un objet exception.  
  
 **ID d’erreur :** BC30666  
  
## <a name="to-correct-this-error"></a>Pour corriger cette erreur  
  
1.  Spécifiez le nom d’un objet d’exception dérivé de `System.Exception`.  
  
2.  Restructurez votre code pour que l’instruction `Throw` se trouve dans un bloc `Catch` .  
  
## <a name="see-also"></a>Voir aussi
- [Throw (instruction)](../../visual-basic/language-reference/statements/throw-statement.md)
- [Try...Catch...Finally (instruction)](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
- [Classe d’exception dans Visual Basic](https://msdn.microsoft.com/library/9aac396f-34ca-4afb-8e6c-e523cb690ba9)
- [Gestion des exceptions et des erreurs en Visual Basic](https://msdn.microsoft.com/library/3e351e73-cf23-40ab-8b60-05794160529e)
