---
title: "&#39; Catch &#39; ne peut pas apparaître en dehors d’un &#39; Essayez de &#39; instruction"
ms.date: 07/20/2015
ms.prod: .net
ms.technology: devlang-visual-basic
ms.topic: article
f1_keywords:
- bc30380
- vbc30380
helpviewer_keywords: BC30380
ms.assetid: 73ce950d-881f-4532-8024-40a4930abd32
caps.latest.revision: "7"
author: dotnet-bot
ms.author: dotnetcontent
ms.openlocfilehash: defb7563950828014cb4a8293fe6e70d4777ee72
ms.sourcegitcommit: 34ec7753acf76f90a0fa845235ef06663dc9e36e
ms.translationtype: MT
ms.contentlocale: fr-FR
ms.lasthandoff: 12/21/2017
---
# <a name="39catch39-cannot-appear-outside-a-39try39-statement"></a>&#39; Catch &#39; ne peut pas apparaître en dehors d’un &#39; Essayez de &#39; instruction
`Catch` doit apparaître dans un bloc d’instruction `Try...Catch...Finally` . Soit vous avez une instruction `Catch` inutile dans votre bloc `Try` , soit votre instruction `Catch` apparaît en dehors des limites de son bloc `Try` .  
  
 **ID d’erreur :** BC30380  
  
## <a name="to-correct-this-error"></a>Pour corriger cette erreur  
  
1.  Supprimez l’instruction `Catch` si elle n’est pas nécessaire, ou placez-la dans un bloc d’instruction `Try...Catch...Finally` .  
  
## <a name="see-also"></a>Voir aussi  
 [Try...Catch...Finally (instruction)](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)  
 
