---
title: L’instruction 'Throw' ne peut pas omettre l’opérande en dehors d’une instruction 'Catch' ou dans une instruction 'Finally'
ms.date: 07/20/2015
f1_keywords:
- vbc30666
- bc30666
helpviewer_keywords:
- BC30666
ms.assetid: a208a6ea-0e36-4bf1-8984-4de1a0e38a2a
ms.openlocfilehash: 6906cb743e6f36acfbf51a5a38d03bd05fde98e2
ms.sourcegitcommit: 6b308cf6d627d78ee36dbbae8972a310ac7fd6c8
ms.translationtype: MT
ms.contentlocale: fr-FR
ms.lasthandoff: 01/23/2019
ms.locfileid: "54598761"
---
# <a name="throw-statement-cannot-omit-operand-outside-a-catch-statement-or-inside-a-finally-statement"></a><span data-ttu-id="fb8c6-102">L’instruction 'Throw' ne peut pas omettre l’opérande en dehors d’une instruction 'Catch' ou dans une instruction 'Finally'</span><span class="sxs-lookup"><span data-stu-id="fb8c6-102">'Throw' statement cannot omit operand outside a 'Catch' statement or inside a 'Finally' statement</span></span>
<span data-ttu-id="fb8c6-103">Les instructions`Throw` situées en dehors de l’instruction `Catch` doivent fournir le nom d’un objet exception.</span><span class="sxs-lookup"><span data-stu-id="fb8c6-103">`Throw` statements outside of `Catch` statement must supply the name of an exception object.</span></span>  
  
 <span data-ttu-id="fb8c6-104">**ID d’erreur :** BC30666</span><span class="sxs-lookup"><span data-stu-id="fb8c6-104">**Error ID:** BC30666</span></span>  
  
## <a name="to-correct-this-error"></a><span data-ttu-id="fb8c6-105">Pour corriger cette erreur</span><span class="sxs-lookup"><span data-stu-id="fb8c6-105">To correct this error</span></span>  
  
1.  <span data-ttu-id="fb8c6-106">Spécifiez le nom d’un objet d’exception dérivé de `System.Exception`.</span><span class="sxs-lookup"><span data-stu-id="fb8c6-106">Specify the name of an exception object derived from `System.Exception`.</span></span>  
  
2.  <span data-ttu-id="fb8c6-107">Restructurez votre code pour que l’instruction `Throw` se trouve dans un bloc `Catch` .</span><span class="sxs-lookup"><span data-stu-id="fb8c6-107">Restructure your code so that the `Throw` statement is inside a `Catch` block.</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="fb8c6-108">Voir aussi</span><span class="sxs-lookup"><span data-stu-id="fb8c6-108">See also</span></span>
- [<span data-ttu-id="fb8c6-109">Throw (instruction)</span><span class="sxs-lookup"><span data-stu-id="fb8c6-109">Throw Statement</span></span>](../../visual-basic/language-reference/statements/throw-statement.md)
- [<span data-ttu-id="fb8c6-110">Try...Catch...Finally (instruction)</span><span class="sxs-lookup"><span data-stu-id="fb8c6-110">Try...Catch...Finally Statement</span></span>](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
- [<span data-ttu-id="fb8c6-111">Classe d’exception dans Visual Basic</span><span class="sxs-lookup"><span data-stu-id="fb8c6-111">Exception Class in Visual Basic</span></span>](https://msdn.microsoft.com/library/9aac396f-34ca-4afb-8e6c-e523cb690ba9)
- [<span data-ttu-id="fb8c6-112">Gestion des exceptions et des erreurs en Visual Basic</span><span class="sxs-lookup"><span data-stu-id="fb8c6-112">Exception and Error Handling in Visual Basic</span></span>](https://msdn.microsoft.com/library/3e351e73-cf23-40ab-8b60-05794160529e)
